server:
    port: 8081

spring:
    datasource:
        url: jdbc:h2:mem:saga-choreography
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    
    application:
        name: InventoryService
    cloud:
        function:
            definition: inventoryProcessor
        stream:            
            bindings:
                inventoryProcessor-in-0:
                    destination: order-event
                inventoryProcessor-out-0:
                    destination: inventory-event
            kafka:
                binder: 
                    brokers: localhost:9092

logging:
  level:
    org:
        apache:
            kafka: INFO
        springframework:
            kafka: INFO

