server:
    port: 8082

spring:
    datasource:
        url: jdbc:h2:mem:saga-choreography
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    
    application:
        name: PaymentService
    cloud:
        function:
            definition: paymentProcessor
        stream:            
            bindings:
                paymentProcessor-in-0:
                    destination: order-event
                paymentProcessor-out-0:
                    destination: payment-event
            kafka:
                binder: 
                    brokers: localhost:9092