server:
    port: 8080

spring:
    datasource:
        url: jdbc:h2:mem:saga-choreography
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    
    application:
        name: OrderService
    cloud:
        function:
            definition: orderSupplier;paymentEventConsumer;inventoryEventConsumer
        stream:            
            bindings:
                orderSupplier-out-0:
                    destination: order-event
                    content-type: application/json
                paymentEventConsumer-in-0:
                    destination: payment-event
                inventoryEventConsumer-in-0:
                    destination: inventory-event
            kafka:
                binder: 
                    brokers: localhost:9092

logging:
  level:
    org:
        apache:
            kafka: INFO
        springframework:
            kafka: INFO
